#! /bin/sh

bspc monitor -d I II III IV V VI VII

bspc config automatic_scheme alternate
bspc config initial_polarity second_child

bspc config border_width 1
bspc config window_gap 10

bspc config top_padding 40
bspc config left_padding 2
bspc config right_padding 2
bspc config bottom_padding 2

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config focus_follows_pointer true
bspc config center_pseudo_tiled true

bspc config pointer_modifier mod1
bspc config pointer_action3 resize_side
bspc config pointer_action3 resize_corner
bspc config pointer_action1 move

bspc rule -a Docky layer=above manage=on border=off focus=off locked=on
bspc rule -a firefox desktop=^1 follow=on
bspc rule -a tellico desktop=^2 follow=on
bspc rule -a code-oss desktop=^3 follow=on
bspc rule -a libreoffice-startcenter desktop=^4 follow=on
bspc rule -a libreoffice-calc=^4 follow=on
bspc rule -a libreoffice-writer=^4 follow=on
bspc rule -a libreoffice-impress=^4 follow=on
bspc rule -a retroarch desktop=^5 follow=on
bspc rule -a quassel desktop=^6 follow=on
bspc rule -a Deluge-gtk desktop=^7 follow=on
bspc rule -a Gourmet follow=on state=tiled
bspc rule -a Thunar follow=on
bspc rule -a Wrapper-2.0 state=floating
bspc rule -a MPlayer state=floating
bspc rule -a Xfce4-settings-manager follow=on state=tiled
bspc rule -a Xfce4-notes state=floating rectangle=500x500+1250+100
bspc rule -a Galculator follow=on state=floating
bspc rule -a Orage state=floating